server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybites
    username: root
    password: Vinnie@123
  jpa:
    hibernate:

      ddl-auto: validate  #when we execute the table will be updated
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations
    validateOnMigrate: false
